name: nextflow_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bwa=0.7.17
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - coreutils=8.25
  - curl=8.8.0
  - eigen=3.4.0
  - entrez-direct=24.0
  - expat=2.7.3
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.14.2
  - freebayes=1.3.6
  - freetype=2.12.1
  - gawk=5.3.1
  - gmp=6.3.0
  - graalpy=23.0.0
  - graalpy-graalvm=23.0.0
  - groovy=5_0_4
  - htslib=1.21
  - jsoncpp=1.9.6
  - keyutils=1.6.3
  - krb5=1.21.3
  - libasprintf=0.25.1
  - libcurl=8.8.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnghttp2=1.58.0
  - libpng=1.6.43
  - libssh2=1.11.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libunistring=0.9.10
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - mafft=7.525
  - mpfr=4.2.1
  - ncurses=6.5
  - nextflow=25.10.3
  - openjdk=17.0.7.4
  - openssl=3.6.1
  - packaging=26.0
  - parallel=20251122
  - patch=2.8
  - perl=5.32.1
  - pip=25.3
  - python=3.10.8
  - python_abi=3.10
  - readline=8.3
  - samtools=1.16.1
  - setuptools=80.10.1
  - tabixpp=1.1.2
  - tk=8.6.13
  - trimal=1.5.0
  - vcflib=1.0.10
  - wfa2-lib=2.3.5
  - wget=1.21.4
  - wheel=0.46.3
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - zlib=1.2.13
  - zstd=1.5.6
